CREATE DATABASE IF NOT EXISTS MEDALLION_DB ;
USE DATABASE MEDALLION_DB;


CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE WAREHOUSE IF NOT EXISTS MEDALLION_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE ;


USE SCHEMA MEDALLION_DB.BRONZE;

CREATE STAGE IF NOT EXISTS RAW_STAGE
    COMMENT = 'Internal Stage for raw CSV files';  

    
LIST @RAW_STAGE
