-- ACCESS_MANAGEMNET --

-- Create a role for the team that loads Bronze data (ingestion role)
CREATE ROLE IF NOT EXISTS BRONZE_LOADER;

-- Create a role for the team that transforms to Silver
CREATE ROLE IF NOT EXISTS SILVER_TRANSFORMER;

-- Create a role for analysts who only read Gold data
CREATE ROLE IF NOT EXISTS GOLD_READER;

-- Grant permissions to each role

-- Bronze Loader can insert into Bronze tables only
GRANT USAGE ON DATABASE MEDALLION_DB TO ROLE BRONZE_LOADER;
GRANT USAGE ON SCHEMA MEDALLION_DB.BRONZE TO ROLE BRONZE_LOADER;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA MEDALLION_DB.BRONZE TO ROLE BRONZE_LOADER;

-- Silver Transformer can read Bronze and write to Silver
GRANT USAGE ON SCHEMA MEDALLION_DB.BRONZE TO ROLE SILVER_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA MEDALLION_DB.BRONZE TO ROLE SILVER_TRANSFORMER;
GRANT USAGE ON SCHEMA MEDALLION_DB.SILVER TO ROLE SILVER_TRANSFORMER;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA MEDALLION_DB.SILVER TO ROLE SILVER_TRANSFORMER;

-- Gold Reader can only SELECT from Gold -- no writes
GRANT USAGE ON SCHEMA MEDALLION_DB.GOLD TO ROLE GOLD_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA MEDALLION_DB.GOLD TO ROLE GOLD_READER;

-- Grant warehouse access to all roles
GRANT USAGE ON WAREHOUSE MEDALLION_WH TO ROLE BRONZE_LOADER;
GRANT USAGE ON WAREHOUSE MEDALLION_WH TO ROLE SILVER_TRANSFORMER;
GRANT USAGE ON WAREHOUSE MEDALLION_WH TO ROLE GOLD_READER;
